### PR TITLE
Custom rule

### PR DESCRIPTION
**Pull request by ashokaditya**

### CODE REVIEW

**Comment by uninth** [comment]
## Port specification(s):

### Range:

The lowest port numer for filtering is 0, while the largest port number is an
unsigned short 2^16-1: 65535, as specified in RFC 793. Port 0 which is not a
valid port may be set in a UDP or TCP package and transported 'over the wire',
see [Port Authority Database, Port 0](https://www.grc.com/port_0.htm)

### Filter specification(s):

For each rule only one of the following syntaxes are allowed:

  - **range**: _lower boundary_ - _upper boundary_, e.g. `=80-8080`
  - **any combination of**: `=port =port >=port <=port ...` e.g. `=80 =443 <=1023`

The `&` sign is not accepted by Juniper: it breaks the BGP sesstion.

You may not specify both a range and something else.


## Package length specification(s):

Here the length of an IP datagram is messured, so the range is between 20 and
65535 (bytes).

### Range:

Size of Ethernet frame - 24 Bytes
Size of IPv4 Header (without any options) - 20 bytes
Size of TCP Header (without any options) - 20 Bytes
So total size of empty TCP datagram - 24 + 20 + 20 = 64 bytes

Size of UDP header - 8 bytes
So total size of empty UDP datagram - 24 + 20 + 8 = 52 bytes

But I think you can create an empty IP frame with 20 bytes

The maximum size of an IP datagram is 65535 bytes while jumbo frames
may be 9038 bytes long [see wikipedia](https://en.wikipedia.org/wiki/Jumbo_frame).

I don't think we should impose an upper limit.

### Filter specification(s):

  - **range**: _lower boundary_ - _upper boundary_, e.g. `=20-9000`
  - **any combination of**: `=length =length >=length <=length ...` e.g. `=348 =512 >=1470`


Venlig hilsen / Best regards, Niels Thomas Haugård

--
Niels Thomas Haugård                                      _ __/|
Work    E-mail:   niels.thomas.haugaard@i2.dk             \'x X'
Private E-mail:   thomas@haugaard.net                     =(_o_)=
Private PGP key:  ldap://keyserver.pgp.com                   U
My desk isn't messy  - it's encrypted                      |>o<|

**Comment by ashokaditya** [comment]
This is a precise list 👍  Thanks @uninth

**Comment by ashokaditya** [comment]
@uninth @loregood What do you think about rate limit?
rate limit is in [1, 10^9] ?

**Comment by AndersMundtDue** [comment]
Rate limit is int >= 1

Anders Mundt Due
Technician

________________________________________

**Comment by ashokaditya** [comment]
@AndersMundtDue Is there no upper limit on the rate limit?

**Comment by ashokaditya** [comment]
@TanguiC any suggestions?

**Comment by AndersMundtDue** [comment]
there are plenty of upper limits, but they're not our concern ...   int >= 1  is imho the best check for ratelimit.

The RFC has a type 0x8006 traffic-rate that can be transported, is has a
IEEE.754.1985 float describing bytes per second and a traffic-rate of 0 should result in all traffic being blocked.

The 4 types that can be transported over BGP FlowSpec are:

"
  0x8006 - Flow spec traffic-rate
  0x8007 - Flow spec traffic-action
  0x8008 - Flow spec redirect
  0x8009 - Flow spec traffic-remarking
"

But we're actually sending BGP FlowSpec to a juniper and they say:

"Limit the bandwidth on the flow route. Express the limit in bits per second (bps). Beginning with Junos OS Release 16.1R4, the rate-limit range is [0 through 1000000000000]."

So in that specific release they have an upper limit of 1Tb/s which is 10 times our current capacity, we're also running Junos 17.1 and planning to get to Junos 17.1R3 which may or may not have a different upper limit.

Still, I would say that all that is largely irrelevant for us and that int >0 would serve the website well as a simple check.

**Comment by AndersMundtDue** [comment]
juniper stuff is from https://www.juniper.net/documentation/en_US/junos/topics/concept/flow-routes-understanding.html  in case you want to look :-)

**Comment by ashokaditya** [comment]
Thanks for the input @AndersMundtDue. @loregood suggested yesterday we have an upper limit of 10^11 which is 10 times less than Juniper's, just as you mention above. Shall we keep that for now if everyone agrees?

**Comment by ashokaditya** [comment]
Super! Tagged this conversation to #37

**Pull request merged**
